//! Codex configuration allowlists, verified against the live schema on 2026-07-16.
//!
//! Keep these values together so schema updates are a localized maintenance change.

pub const APPROVAL_POLICIES: &[&str] = &["untrusted", "on-request", "never"];
pub const SANDBOX_MODES: &[&str] = &["read-only", "workspace-write", "danger-full-access"];
pub const REASONING_EFFORTS: &[&str] = &["none", "minimal", "low", "medium", "high", "xhigh"];
pub const VERBOSITIES: &[&str] = &["low", "medium", "high"];
pub const PERSONALITIES: &[&str] = &["none", "friendly", "pragmatic"];
pub const CREDENTIAL_STORES: &[&str] = &["file", "keyring", "auto", "ephemeral"];
pub const MCP_CREDENTIAL_STORES: &[&str] = &["file", "keyring", "auto"];
pub const REASONING_SUMMARIES: &[&str] = &["auto", "none", "concise", "detailed"];
pub const APPROVAL_REVIEWERS: &[&str] = &["user", "auto_review", "guardian_subagent"];
pub const SERVICE_TIERS: &[&str] = &["default", "priority", "flex", "fast"];
pub const SHELL_INHERIT_VALUES: &[&str] = &["core", "all", "none"];
pub const APP_APPROVAL_MODES: &[&str] = &["auto", "prompt", "writes", "approve"];
pub const WORKSPACE_WRITE_MODES: &[&str] = &["allowlist", "denylist", "all"];

pub const TOP_LEVEL_KEYS: &[&str] = &[
    "agents",
    "allow_login_shell",
    "analytics",
    "approval_policy",
    "approvals_reviewer",
    "apps",
    "apps_mcp_product_sku",
    "audio",
    "auto_review",
    "background_terminal_max_timeout",
    "chatgpt_base_url",
    "check_for_update_on_startup",
    "cli_auth_credentials_store",
    "compact_prompt",
    "debug",
    "default_permissions",
    "desktop",
    "developer_instructions",
    "disable_paste_burst",
    "experimental_compact_prompt_file",
    "experimental_realtime_start_instructions",
    "experimental_realtime_webrtc_call_base_url",
    "experimental_realtime_ws_backend_prompt",
    "experimental_realtime_ws_base_url",
    "experimental_realtime_ws_model",
    "experimental_realtime_ws_startup_context",
    "experimental_thread_config_endpoint",
    "experimental_thread_store",
    "experimental_use_unified_exec_tool",
    "features",
    "feedback",
    "file_opener",
    "forced_chatgpt_workspace_id",
    "forced_login_method",
    "ghost_snapshot",
    "hide_agent_reasoning",
    "history",
    "hooks",
    "include_apps_instructions",
    "include_collaboration_mode_instructions",
    "include_environment_context",
    "include_permissions_instructions",
    "instructions",
    "log_dir",
    "marketplaces",
    "mcp_oauth_callback_port",
    "mcp_oauth_callback_url",
    "mcp_oauth_credentials_store",
    "mcp_servers",
    "memories",
    "model",
    "model_auto_compact_token_limit",
    "model_auto_compact_token_limit_scope",
    "model_catalog_json",
    "model_context_window",
    "model_instructions_file",
    "model_provider",
    "model_providers",
    "model_reasoning_effort",
    "model_reasoning_summary",
    "model_supports_reasoning_summaries",
    "model_verbosity",
    "notice",
    "notify",
    "openai_base_url",
    "orchestrator",
    "oss_provider",
    "otel",
    "permissions",
    "personality",
    "plan_mode_reasoning_effort",
    "plugins",
    "profile",
    "profiles",
    "project_doc_fallback_filenames",
    "project_doc_max_bytes",
    "project_root_markers",
    "projects",
    "realtime",
    "review_model",
    "sandbox_mode",
    "sandbox_workspace_write",
    "service_tier",
    "shell_environment_policy",
    "show_raw_agent_reasoning",
    "skills",
    "sqlite_home",
    "suppress_unstable_features_warning",
    "tool_output_token_limit",
    "tool_suggest",
    "tools",
    "tui",
    "web_search",
    "windows",
];

pub const FEATURE_KEYS: &[&str] = &[
    "apply_patch_freeform",
    "apply_patch_streaming_events",
    "apps",
    "apps_mcp_path_override",
    "auth_elicitation",
    "browser_use",
    "browser_use_external",
    "browser_use_full_cdp_access",
    "chronicle",
    "code_mode",
    "code_mode_host",
    "code_mode_only",
    "codex_git_commit",
    "codex_hooks",
    "collab",
    "collaboration_modes",
    "computer_use",
    "concurrent_reasoning_summaries",
    "connectors",
    "current_time_reminder",
    "default_mode_request_user_input",
    "deferred_executor",
    "elevated_windows_sandbox",
    "enable_experimental_windows_sandbox",
    "enable_fanout",
    "enable_mcp_apps",
    "enable_request_compression",
    "exec_permission_approvals",
    "experimental_use_unified_exec_tool",
    "experimental_windows_sandbox",
    "external_migration",
    "fast_mode",
    "goals",
    "guardian_approval",
    "hooks",
    "image_detail_original",
    "image_generation",
    "imagegenext",
    "in_app_browser",
    "item_ids",
    "js_repl",
    "js_repl_tools_only",
    "local_thread_store_compression",
    "memories",
    "memory_tool",
    "mentions_v2",
    "multi_agent",
    "multi_agent_mode",
    "multi_agent_v2",
    "network_proxy",
    "non_prefixed_mcp_tool_names",
    "personality",
    "plugin_hooks",
    "plugin_sharing",
    "plugins",
    "prevent_idle_sleep",
    "realtime_conversation",
    "remote_compaction_v2",
    "remote_control",
    "remote_models",
    "remote_plugin",
    "request_permissions",
    "request_permissions_tool",
    "request_rule",
    "resize_all_images",
    "respect_system_proxy",
    "responses_websockets",
    "responses_websockets_v2",
    "rollout_budget",
    "runtime_metrics",
    "search_tool",
    "secret_auth_storage",
    "shell_snapshot",
    "shell_tool",
    "shell_zsh_fork",
    "skill_env_var_dependency_prompt",
    "skill_mcp_dependency_install",
    "sqlite",
    "standalone_web_search",
    "steer",
    "telepathy",
    "terminal_resize_reflow",
    "terminal_visualization_instructions",
    "token_budget",
    "tool_call_mcp_elicitation",
    "tool_search",
    "tool_search_always_defer_mcp_tools",
    "tool_suggest",
    "tui_app_server",
    "unavailable_dummy_tools",
    "undo",
    "unified_exec",
    "unified_exec_zsh_fork",
    "use_agent_identity",
    "use_legacy_landlock",
    "use_linux_sandbox_bwrap",
    "web_search",
    "web_search_cached",
    "web_search_request",
    "workspace_dependencies",
    "workspace_owner_usage_nudge",
];

pub const TUI_KEYS: &[&str] = &[
    "alternate_screen",
    "animations",
    "keymap",
    "model_availability_nux",
    "notification_condition",
    "notification_method",
    "notifications",
    "pet",
    "pet_anchor",
    "raw_output_mode",
    "session_picker_view",
    "show_tooltips",
    "status_line",
    "status_line_use_colors",
    "terminal_resize_reflow_max_rows",
    "terminal_title",
    "theme",
    "vim_mode_default",
];
pub const SHELL_POLICY_KEYS: &[&str] = &[
    "exclude",
    "experimental_use_profile",
    "ignore_default_excludes",
    "include_only",
    "inherit",
    "set",
];
pub const MCP_SERVER_KEYS: &[&str] = &[
    "args",
    "auth",
    "bearer_token",
    "bearer_token_env_var",
    "command",
    "cwd",
    "default_tools_approval_mode",
    "disabled_tools",
    "enabled",
    "enabled_tools",
    "env",
    "env_http_headers",
    "env_vars",
    "environment_id",
    "http_headers",
    "name",
    "oauth",
    "oauth_resource",
    "required",
    "scopes",
    "startup_timeout_ms",
    "startup_timeout_sec",
    "supports_parallel_tool_calls",
    "tool_timeout_sec",
    "tools",
    "url",
];
pub const APP_KEYS: &[&str] = &[
    "approvals_reviewer",
    "default_tools_approval_mode",
    "default_tools_enabled",
    "destructive_enabled",
    "enabled",
    "open_world_enabled",
    "tools",
];
pub const APP_DEFAULT_KEYS: &[&str] = &[
    "approvals_reviewer",
    "default_tools_approval_mode",
    "destructive_enabled",
    "enabled",
    "open_world_enabled",
];
pub const NETWORK_PERMISSION_KEYS: &[&str] =
    &["allow", "deny", "enabled", "allow_domains", "deny_domains"];
pub const WINDOWS_SANDBOX_MODES: &[&str] = &["elevated", "unelevated"];
