/// Hard-retired identifiers: `LintRule::from_code_or_name` returns `None`
/// for every entry. A new hard retirement appends its code and name here
/// and nowhere else; every tombstone test iterates this constant.
pub const RETIRED_IDENTIFIERS: &[&str] = &[
    "S012",
    "S013",
    "name-reserved-word",
    "name-has-xml",
    "K001",
    "slack-fallback-mismatch",
    "U003",
    "userconfig-env-missing",
    "I005",
    "instruction-file-structure",
    "CX044",
    "codex-agents-structure",
    "S001",
    "skills-dir-missing",
    "S042",
    "dmi-empty-desc",
    "S045",
    "tools-list-syntax",
    "S049",
    "name-not-gerund",
    "O005",
    "style-name-long",
    "CX046",
    "codex-plugin-path",
    "CX058",
    "codex-plugin-hooks",
    "channels-enabled-invalid",
    "style-field-unknown",
    "CX037",
    "codex-agents-empty",
    "CX038",
    "codex-agents-secret",
    "CX041",
    "codex-agents-path",
    "CX043",
    "codex-agents-generic",
    "codex-agents-limit",
    "codex-agents-conflict",
    "security-md-missing",
];
